language: python
group: travis_latest
dist: xenial

os: linux

python: 3.6

git:
  depth: 3
  quiet: true

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages:
    - octave
    - gfortran

install: pip install -e .

script: octave --eval "runtests('.')"
